name: CI
on: [push]
jobs:
  package:
    runs-on: ubuntu-latest
    container: fedora
    steps: 
    - name: package
      run: |        
        dnf makecache
        dnf in -y gzip git git-lfs fastfetch
    - name: clone src
      run: |
        cd /root
        git clone https://github.com/lwh2008/ll-rh.git
    - name: demo1
      run: |
        cd /root/ll-rh
        bash indep.sh
        cd ..
        tar cjf ll.tbz ll-rh
        ll-cli --version
        free -h
        sudo ll-cli install org.deepin.Foundation
    - name: info
      run: fastfetch
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: /root/ll.tbz
        if-no-files-found: error
        retention-days: 10
