name: CI
on: [push]
jobs:
  package:
    runs-on: ubuntu-latest
    container: fedora
    steps: 
    - name: in-dep
      run: |        
        dnf makecache -y
        dnf up -y
        dnf in -y cmake gcc-c++ qt5-qtbase-devel qt5-qtwebsockets-devel qt5-qtbase-private-devel glib2-devel nlohmann-json-devel ostree-devel yaml-cpp-devel systemd-devel gtest-devel libseccomp-devel elfutils-libelf-devel glibc-static libstdc++-static docopt-cpp-devel git fastfetch
        ln -s /usr/lib64/libdocopt.so /usr/lib64/libdocopt.a
    - name: clone-src
      run: |
        cd /root
        git clone https://github.com/linuxdeepin/linglong /root
    - name: build-src
      run: |
        #mv 1.5.7 linglong
        cd /root/linglong
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)
    - name: info
      run: fastfetch
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ll-build
        path: /root/linglong
        if-no-files-found: error
        retention-days: 10
